# Generated by Django 2.1.3 on 2018-11-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(default='general', max_length=40),
        ),
    ]
