# Generated by Django 2.1.3 on 2018-11-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20181124_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_edited',
            field=models.DateTimeField(null=True),
        ),
    ]
