# Generated by Django 2.1.3 on 2018-11-24 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20181124_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='category',
            new_name='tags',
        ),
    ]
