# Generated by Django 2.1.3 on 2018-11-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20181124_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date_edited',
            field=models.DateTimeField(null=True),
        ),
    ]
