# Generated by Django 2.1.3 on 2018-11-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_auto_20181124_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='attached_image',
            field=models.ImageField(blank=True, null=True, upload_to='userimages/questions'),
        ),
    ]
