# Generated by Django 2.1.3 on 2018-11-26 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_question_attached_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='selected_answer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='questions.Answer'),
        ),
    ]
