# Generated by Django 2.1.3 on 2018-11-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='lat',
            field=models.DecimalField(decimal_places=5, editable=False, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='lng',
            field=models.DecimalField(decimal_places=5, editable=False, max_digits=9, null=True),
        ),
    ]
