# Generated by Django 2.1.3 on 2018-11-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20181120_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='last_modified',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='edit_date',
            field=models.DateTimeField(),
        ),
    ]
