# Generated by Django 2.1.3 on 2018-11-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20181124_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='last_modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='edit_date',
            field=models.DateTimeField(null=True),
        ),
    ]
