# Generated by Django 2.1.3 on 2018-11-24 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listingviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListingViews',
            new_name='ListingView',
        ),
    ]
