# Generated by Django 2.1.3 on 2018-11-24 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20181124_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='sold',
        ),
    ]
