# Generated by Django 2.1.3 on 2018-11-25 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20181124_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='creation_date',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='edit_date',
            new_name='date_edited',
        ),
    ]
