# Generated by Django 2.1.3 on 2018-11-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_auto_20181125_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='avatar',
            field=models.ImageField(default='files/userimages/avatar.gif', upload_to='files/userimages/sellers'),
        ),
    ]
