# Generated by Django 2.1.3 on 2018-11-26 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_seller_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='cached_id',
            new_name='hash',
        ),
    ]
