# Generated by Django 2.1.3 on 2018-11-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_uploadedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='avatar',
            field=models.ImageField(default='userimages/avatar.gif', upload_to='userimages/sellers'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='file',
            field=models.ImageField(upload_to='userimages'),
        ),
    ]
