# Generated by Django 2.1.3 on 2018-11-26 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0013_auto_20181126_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='uploaded',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(upload_to='userimages/listings'),
        ),
    ]
