# Generated by Django 2.1.3 on 2018-11-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_auto_20181126_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='image',
        ),
        migrations.AddField(
            model_name='listing',
            name='images',
            field=models.ManyToManyField(to='listings.UploadedImage'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='avatar',
            field=models.ImageField(blank=True, default='files/userimages/avatar.gif', upload_to='userimages/sellers'),
        ),
    ]
