# Generated by Django 2.1.3 on 2018-11-27 17:49

from django.db import migrations, models
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_listing_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='userimages/listings/271118/thumbnails'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='file',
            field=models.ImageField(upload_to='userimages/listings/271118'),
        ),
    ]
