# Generated by Django 2.1.3 on 2018-11-27 18:10

from django.db import migrations, models
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_auto_20181127_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='userimages/listings/271118'),
        ),
    ]
