# Generated by Django 2.1.3 on 2018-11-27 20:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_auto_20181127_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_emails',
            field=models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.RegexValidator(code='emails_format_incorrect', message='Incorrect format', regex='(\\w+?@\\w+?\\.\\w{2,3},){,2}')]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='social_contacts',
            field=models.CharField(default='{}', max_length=500, validators=[django.core.validators.RegexValidator(code='social_format_incorrect', message='Incorrect format', regex='{("\\w+":"\\S+?",){,3}("\\w+":"\\S+?"){,1}}')]),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='file',
            field=models.ImageField(upload_to='userimages/listings/271118'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='userimages/listings/thumbnails'),
        ),
    ]
