# Generated by Django 2.1.3 on 2018-11-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_auto_20181127_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='call_time',
            field=models.CharField(default='00:00-23:59', max_length=11),
        ),
    ]
