"""
Django settings for inspector project.

Generated by 'django-admin startproject' using Django 2.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SECRET_KEY = '-66%4q&$0r6cha7c@x=uqto-n@fwfxwa7cr+sl=zxf#p)i_-_#'

DEBUG = True

ALLOWED_HOSTS = []

# Application definition
INSTALLED_APPS = [
    'listings.apps.ListingsConfig',
    'questions.apps.QuestionsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
]

SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'
SESSION_COOKIE_HTTP_ONLY = True

ROOT_URLCONF = 'inspector.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'inspector.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'db',
        'USER': 'user',
        'PASSWORD': 'pass',
        'HOST': 'localhost'
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'ru-ru'
LANGUAGES = [
    ('ru', _('Russian')),
    ('en', _('English'))
]
LOCALE_PATHS = [BASE_DIR + '/translations']
TIME_ZONE = 'Europe/Minsk'
USE_I18N = True
USE_L10N = False
USE_TZ = True

RESERVED_KEYWORDS = ['admin', 'seller', 'moderator']

DATE_FORMAT = 'd.m.Y'
DATETIME_FORMAT = 'd.m.y H:i'

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'files')
MEDIA_URL = '/files/'

LOGIN_URL = '/listings/login/'

LOGIN_REDIRECT_URL = '/listings/'
LOGOUT_REDIRECT_URL = '/listings/'

ENTRIES_PER_PAGE = 25

# Used in listings.models
MIN_RATING = 1
MAX_RATING = 5

# Used in listings.views
STAR_SYMBOL = '&#9733;'
EMPTY_STAR_SYMBOL = '&#9734;'
MIN_DESCRIPTION_LENGTH = 10
MAX_PRICE = 99999999

# How many names must the full name consist of
# Mihanov Arkadii Lvovich (3)
# Jakson Ramsey (2)
FULL_NAME_PARTS = 3

# Avatar height (equals to width) in pixels
DEFAULT_AVATAR_HEIGHT = 200
